function calcular1(){
    var sb = document.getElementById('sb')
    var qh = document.getElementById('qh')
    var he = document.getElementById('he')
    var hf = document.getElementById('hf')
    var hn = document.getElementById('hn')
    var n1 = Number(sb.value)
    var n2 = Number(qh.value)
    var n3 = Number(he.value)
    var n4 = Number(hf.value)
    var n5 = Number(hn.value)
    var t1 = document.getElementById('t1')
    var t2 = document.getElementById('t2')
    var t3 = document.getElementById('t3')
    var t4 = document.getElementById('t4')
    var r01 = document.getElementById('r01')
    var r02 = document.getElementById('r02')
    var r03 = document.getElementById('r03')
    var r04 = document.getElementById('r04')
    var vh = n1 / n2
    var ve = vh / 2 + vh
    var vf = vh * 2
    var vn = vh / 100 * 80 + vh
    var vte = ve * n3
    var vtf = vf * n4
    var vtn = vn * n5
    var vts = n1 + vte + vtf + vtn
    var r1 = vh.toFixed(2)
    var r2 = ve.toFixed(2)
    var r3 = vf.toFixed(2)
    var r4 = vn.toFixed(2)
    var vte1 = vte.toFixed(2)
    var vtf2 = vtf.toFixed(2)
    var vtn3 = vtn.toFixed(2)
    var vts4 = vts.toFixed(2)
    var art = document.getElementsByTagName('article')[0]
    var posicao = document.getElementsByClassName('prin03')[0]
    t1.innerHTML = `R$ ${r1}`
    t2.innerHTML = `R$ ${r2}`
    t3.innerHTML = `R$ ${r3}`
    t4.innerHTML = `R$ ${r4}`
    r01.innerHTML = `R$ ${vte1}`
    r02.innerHTML = `R$ ${vtf2}`
    r03.innerHTML = `R$ ${vtn3}`
    r04.innerHTML = `R$ ${vts4}`
    art.style.display = 'block'
    posicao.style.top = '900px'
}
function calcular2(){
    var sal = document.getElementById('sal')
    var desc = document.getElementById('desc')
    var n01 = Number(sal.value)
    var n02 = Number(desc.value)
    var inss1 = document.getElementById('inss1')
    var inss2 = document.getElementById('inss2')
    var irrf1 = document.getElementById('irrf1')
    var irrf2 = document.getElementById('irrf2')
    var total1 = document.getElementById('total1')
    var total2 = document.getElementById('total2')
    var sl1 = document.getElementById('sl1')
    var x1 = n01 / 100 * 7.5
    var x01 = n01 - x1
    var x2 = n01 / 100 * 9
    var x02 = n01 - x2
    var x3 = n01 / 100 * 12
    var x03 = n01 - x3
    var x4 = n01 / 100 * 14
    var x04 = n01 - x4
    var d1 = x1.toFixed(2)
    var d2 = x2.toFixed(2)
    var d3 = x3.toFixed(2)
    var d4 = x4.toFixed(2)
    var d01 = x01.toFixed(2)
    var d02 = x02.toFixed(2)
    var d03 = x03.toFixed(2)
    var d04 = x04.toFixed(2)
    var in1 = '7,5%'
    var in2 = '9%'
    var in3 = '12%'
    var in4 = '14%'
    if (n01 <= 1100){
        inss1.innerText = `${in1}`
        inss2.innerText = `${d1}`
        sl1.innerText = `${d01}`
    }
}